### PR TITLE
Automatically generate an up-to-date `other-installation-method.md`

### LINKED ISSUE #187: Dead link to 'the archives' on https://forge.rust-lang.org/other-installation-methods.html
On https://forge.rust-lang.org/other-installation-methods.html there is a link to 'the archives' leading to https://static.rust-lang.org/dist/index.html, but this seems to be a 404, and, of course, there is no link to the old versions.

### LINKED ISSUE #205: "Other Installation Methods" out of date
# Content Bug Report

## Page(s) Affected

The links on https://forge.rust-lang.org/other-installation-methods.html#standalone only show downloads for the 1.32.0 release.

# What needs to be fixed?

It should always be updated at the same time as the front page gets updated to show the latest release.

Simply fixing the page to show the latest version isn't a fix to this report. A fix to this report is that the latest version always appears when there is a new version.

### PR DESCRIPTION
**Pull request by kennytm**
Added a generator which reads the live channel TOML files to generate the corresponding `_config.yml` before building the page on Travis. 

(Note: We need to add a Travis cron job to actually make this process automatic)

Fixed #205.
Fixed #187 (removed the dead-link).

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -0,0 +1,121 @@
...
+        pub rust: Rust,
+    }
+
+    #[derive(Deserialize)]
+    pub struct Channel {
+        pub pkg: Packages,
+    }
+}
+
+mod travis {
```
Comment (pietroalbini) [inline src/main.rs]: Why this module? It doesn't seem to be used anywhere.

File: .travis.yml [hunk 2]
```diff
@@ -1,15 +1,12 @@
-language: ruby
-rvm:
-- 2.3
-
-# Containers are cool!
-sudo: false
+language: rust
```
Comment (pietroalbini) [inline .travis.yml]: Can you add `cache: cargo` to speed up the build?

**Comment by pietroalbini** [comment]
Also configured the cronjob.
